

//
//Nguyen Khac Huy - 2280601183
//Have a nice day
//
package readwritebinarytext;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author khach
 */
public class frmMain extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmMain.class.getName());

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fcPath = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPath = new javax.swing.JTextField();
        txtChuoi = new javax.swing.JTextField();
        btnReadNP = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtNoiDung = new javax.swing.JTextField();
        btnWriteNP = new javax.swing.JButton();
        btnReadVB = new javax.swing.JButton();
        btnWriteVB = new javax.swing.JButton();
        btnGetFile = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Path file: ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Nhập Chuỗi: ");

        btnReadNP.setText("Read N.Phân");
        btnReadNP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReadNPActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("ND file: ");

        btnWriteNP.setText("Write N.Phân");
        btnWriteNP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWriteNPActionPerformed(evt);
            }
        });

        btnReadVB.setText("Read VB");
        btnReadVB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReadVBActionPerformed(evt);
            }
        });

        btnWriteVB.setText("Write VB");
        btnWriteVB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWriteVBActionPerformed(evt);
            }
        });

        btnGetFile.setText("GetFile");
        btnGetFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnReadNP, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnWriteNP, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnReadVB, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnWriteVB, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtChuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNoiDung, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtPath, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnGetFile, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGetFile))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(txtChuoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(txtNoiDung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReadNP)
                    .addComponent(btnWriteNP))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReadVB)
                    .addComponent(btnWriteVB))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnWriteVBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWriteVBActionPerformed
        //BD
        try{
            File file=new File(txtPath.getText());
            FileWriter fw=new FileWriter(file);
            //gh nd vao file
            fw.write(txtChuoi.getText());
            fw.close();
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
        
        
    }//GEN-LAST:event_btnWriteVBActionPerformed

    private void btnGetFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetFileActionPerformed
        //bd
        //C1: Chon File
        //show fc+ lay KQ
        int result=fcPath.showDialog(this, "Chọn");
        //Neu chon file
        if(result==JFileChooser.APPROVE_OPTION){
            //0 | 0
            File file =fcPath.getSelectedFile();
            String path=file.getAbsolutePath();
            //dan
            txtPath.setText(path);
            
        }
    }//GEN-LAST:event_btnGetFileActionPerformed

    private void btnWriteNPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWriteNPActionPerformed
        //ghi file
        byte []a=new byte[20];
        File file;
        //bien txtChuoi.getText() thanh Array
        //dk chuoi
        if(txtChuoi.getText().length()>=20){
            JOptionPane.showMessageDialog(this, "Chuỗi <= 20 thôi :)))");
            txtChuoi.setText("");
            return;
        }
        char []s=txtChuoi.getText().toCharArray();
        for(int i=0;i<s.length;i++){
            //dan nd for a
            a[i]=(byte)s[i];
        }
        
        try{//FileOutputStream=> ghi NP
                        //absPath: C:\test\Test.txt
            file=new File(txtPath.getText());//
            FileOutputStream fo=new FileOutputStream(file);
            //ghi nd mang a vao file
            fo.write(a);
            fo.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "error: "+e);
        }
        
        
        
    }//GEN-LAST:event_btnWriteNPActionPerformed

    private void btnReadNPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadNPActionPerformed
        //read NP
        try{
            byte []a;
            File file=new File(txtPath.getText());
            FileInputStream fi=new FileInputStream(file);
            a=new byte[fi.available()];
            //doc file roi chuyen nd => a
            fi.read(a);
            fi.close();
            txtNoiDung.setText(new String(a));
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
        
    }//GEN-LAST:event_btnReadNPActionPerformed

    private void btnReadVBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadVBActionPerformed
        //BD
        //Doc A->Z
//        try {
//            File file = new File(txtPath.getText());
//            FileReader fr = new FileReader(file);
//            //System.out.println("sl byte co the doc: "+file.length());
//            int c;
//            char []a=new char[(int)file.length()];
//            String content;
//            int i=0;
//            while((c=fr.read())!=-1 ){
//                a[i]=(char)c;
//                i++;
//            }
//            //Chuyen char[]=> String
//            fr.close();
//            content=new String(a);
//            JOptionPane.showMessageDialog(this, "ND file: "+content);
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(this, e);
//        }

        //Doc theo SL nhat dinh
        try {
            File file = new File(txtPath.getText());
            FileReader fr = new FileReader(file);
            //class x.dung String
            StringBuffer sb=new StringBuffer();
            char []a=new char[5];//doc 5k.tu moi lan
            while(fr.ready()){
                //doc 5k.tu_. save-> a,
                //tr.ve sl k.tu doc dc "len"
                int len=fr.read(a);
                sb.append(a, 0, len);
            }
            JOptionPane.showMessageDialog(this, "ND: "+sb);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }

        
        
        
    }//GEN-LAST:event_btnReadVBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmMain().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGetFile;
    private javax.swing.JButton btnReadNP;
    private javax.swing.JButton btnReadVB;
    private javax.swing.JButton btnWriteNP;
    private javax.swing.JButton btnWriteVB;
    private javax.swing.JFileChooser fcPath;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtChuoi;
    private javax.swing.JTextField txtNoiDung;
    private javax.swing.JTextField txtPath;
    // End of variables declaration//GEN-END:variables
}
